environment:
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_TOOLCHAIN: 1.29.0

branches:
  only:
    - master

cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target'

clone_depth: 1

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - cargo check --verbose --release --all-targets --features=dump-graphs

test_script:
  - cargo test --verbose --release
  - cargo test --verbose --release --features=testing,malice-detection
  - cargo test --verbose --release --features=dump-graphs dot_parser
